name: push
on:
  push:
    branches: [ main ]
jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DH_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.5.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies 
        run: npm ci
      - name: Run tests 
        run: npm run test
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage/libs/ngx-dynamic-headings
      - name: Make build.sh executable
        run: chmod +x build.sh
      - name: Create a Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.DH_PAT }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
      - name: Check if directory exists
        run: |
          if [ -d ./dist/libs/ngx-dynamic-headings ]; then
            echo "New lib build directory exists"
            echo "NEW_LIB_BUILD=true" >> $GITHUB_ENV
          else
            echo "New lib build does not exist"
            echo "NEW_LIB_BUILD=false" >> $GITHUB_ENV
          fi
      - name: Publish to npm
        if: ${{ env.NEW_LIB_BUILD == 'true' }}
        run: |
          cd ./dist/libs/ngx-dynamic-headings
          ls
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}